### ISSUE TITLE
Tests not working for Python 3

### ISSUE THREAD

**Issue by dnmellen** [Feverup/pysugarcrm#1]
@iknite We need to fix the tests for Python 3 so travis badge go green...

**Comment by arnaudlamy** [comment]
Done for python 3.3 & 3.4.

**Comment by dnmellen** [comment]
@arnaudlamy It seems Travis is still not passing :(

The error seems like it is unable to load the tests in Python 3.

**Comment by arnaudlamy** [comment]
Yep an issue with python3.2 I didn't test this version I will if I have times.

**Comment by iknite** [comment]
@dnmellen  I think we can drop 3.2 support, as django are also dropping it.

**Comment by arnaudlamy** [comment]
So it works :)

**Comment by iknite** [comment]
As far as I can see the your  PR @arnaudlamy are still 3.4, and 3.3 broken (please note that the first column are the build number not the python version) and there is no 3.2 build

https://travis-ci.org/Feverup/pysugarcrm/builds/109802604

**Comment by arnaudlamy** [comment]
Sorry for the mistake I will check then.

**Comment by iknite** [comment]
Thanks! That will be awesome! :beers:
